name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t alexandrevoliveira/react-test -f ./docker/complex/client/Dockerfile.dev ./docker/complex/client
      - run: docker run -e CI=true alexandrevoliveira/react-test npm test

      - run: docker build -t alexandrevoliveira/multi-client ./docker/complex/client
      - run: docker build -t alexandrevoliveira/multi-nginx ./docker/complex/nginx
      - run: docker build -t alexandrevoliveira/multi-server ./docker/complex/server
      - run: docker build -t alexandrevoliveira/multi-worker ./docker/complex/worker

      - run: docker push alexandrevoliveira/multi-client
      - run: docker push alexandrevoliveira/multi-nginx
      - run: docker push alexandrevoliveira/multi-server
      - run: docker push alexandrevoliveira/multi-worker

      - name: Generate deployment package
        run: zip -r deploy-docker-complex.zip ./docker/complex -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env-1
          existing_bucket_name: elasticbeanstalk-sa-east-1-437149323516
          region: sa-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy-docker-complex.zip
